apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: myapp-image:local
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"  # Maximum of 0.5 CPU cores
            memory: "512Mi"  # Maximum of 512 megabytes
          requests:
            cpu: "0.2"  # Initial request of 0.2 CPU cores
            memory: "256Mi"  # Initial request of 256 megabytes

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
