version: "3"

services:
  app:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - "8081:8080"
    volumes:
      - mydata:/app/data  # Mount the 'mydata' named volume to the /app/data directory in the container

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  mydata:  # Define the 'mydata' named volume
